export const mockDashboard = {
  user: {
    id: 1,
    first_name: 'John',
    last_name: 'Doe',
    email: 'john@example.com',
  },
  events: [
    {
      id: 1,
      date: '2025-06-25',
      type: 'birthday',
      title: "Dad's Birthday",
      contactId: 2,
    },
    {
      id: 2,
      date: '2025-06-28',
      type: 'general',
      title: 'Coffee with Sarah',
      contactId: 3,
    },
  ],
  notifications: [
    {
      id: 1,
      type: 'UPCOMING_EVENT',
      message: "Dad's birthday is in 3 days",
      eventId: 1,
      date: 'March 25, 2024',
    },
    {
      id: 2,
      type: 'NO_CONTACT',
      message: 'Check in with Sarah',
      contactId: 3,
      daysSince: 45,
    },
    {
      id: 3,
      type: 'UPCOMING_EVENT',
      message: 'Coffee meetup with Sarah',
      eventId: 2,
      date: 'March 28, 2024',
    },
  ],
};

export const mockContacts = [
  {
    id: 1,
    firstName: 'Sarah',
    lastName: 'Johnson',
    birthday: '1990-05-15',
    lastContactDate: '2024-01-15', // 45+ days ago
    email: 'sarah.j@example.com',
    phone: '+1234567890',
    notes: 'Loves photography, prefers texts over calls',
    tags: ['friend', 'photography'],
  },
  {
    id: 2,
    firstName: 'Robert',
    lastName: 'Smith',
    birthday: '1965-03-25',
    lastContactDate: '2024-03-01',
    relationship: 'Dad',
    phone: '+1987654321',
    notes: 'Retirement planning, weekly Sunday calls',
    tags: ['family'],
  },
  {
    id: 3,
    firstName: 'Emma',
    lastName: 'Davis',
    birthday: '1992-08-10',
    lastContactDate: '2024-03-20',
    email: 'emma.d@example.com',
    phone: '+1122334455',
    notes: 'Book club every month, coffee enthusiast',
    tags: ['friend', 'book club'],
  },
  {
    id: 4,
    firstName: 'Michael',
    lastName: 'Wilson',
    birthday: '1969-02-15',
    lastContactDate: '2024-02-15',
    email: 'mike.w@example.com',
    phone: '+1555666777',
    notes: 'Met at tech conference, working on potential collaboration',
    tags: ['professional', 'tech'],
  },
  {
    id: 5,
    firstName: 'Lisa',
    lastName: 'Brown',
    birthday: '2003-6-16',
    lastContactDate: '2025-02-15',
    email: 'lisa.b@example.com',
    phone: '+1999888777',
    notes: 'Yoga instructor, monthly wellness sessions',
    tags: ['fitness', 'wellness'],
  },
]; 