# Generated by Django 5.2.4 on 2025-08-03 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='contact_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='contact_id',
        ),
        migrations.AddField(
            model_name='event',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_related', to='accounts.person'),
        ),
        migrations.AddField(
            model_name='notification',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_related', to='accounts.person'),
        ),
    ]
