# Generated by Django 5.2.4 on 2025-07-23 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_user',
            field=models.ForeignKey(blank=True, help_text='If this contact is another registered user, reference them here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('contact_user__isnull', False)), fields=('user', 'contact_user'), name='unique_contact_user_pair'),
        ),
    ]
