# Generated by Django 5.2.4 on 2025-08-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_person_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='last_contact_date',
            field=models.DateField(blank=True, help_text='Date of the most recent interaction', null=True),
        ),
    ]
