# Generated by Django 5.2.4 on 2025-08-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_connection_last_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='no_contact_threshold',
            field=models.IntegerField(default=30, help_text='Number of days after which to generate a no-contact notification for this connection'),
        ),
    ]
