# Generated by Django 5.2.4 on 2025-08-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_connection_no_contact_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='no_contact_threshold',
            field=models.IntegerField(blank=True, help_text='Number of days after which to generate a no-contact notification for this connection. Null means no notifications.', null=True),
        ),
    ]
