# Generated by Django 5.2.4 on 2025-09-14 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_person_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='tags',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The user (Person) who created this tag.', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='accounts.person')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AddField(
            model_name='connection',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='connections', to='accounts.tag'),
        ),
    ]
