# Generated by Django 5.2.4 on 2025-09-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_person_tags_tag_connection_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#cccccc', help_text='Hex color like #FF0000', max_length=7),
        ),
    ]
