# Generated by Django 5.2.4 on 2025-09-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='User-defined tags to group events and connect them to contacts.', related_name='events', to='accounts.tag'),
        ),
    ]
