# Generated by Django 5.2.4 on 2025-09-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_person_nullable'),
    ]

    operations = [
    ]
