# Generated by Django 5.2.4 on 2025-09-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_null_account_person_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='person',
        ),
        migrations.AddField(
            model_name='event',
            name='people',
            field=models.ManyToManyField(blank=True, help_text='People associated with this event.', related_name='events_related', to='accounts.person'),
        ),
    ]
