# Generated by Django 5.2.4 on 2025-09-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_event_person_event_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='extra_contacts',
            field=models.JSONField(blank=True, default=list, help_text='Additional contact infos beyond phone/email. List of {type, value} objects.'),
        ),
    ]
