# Generated by Django 5.2.4 on 2025-09-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_person_extra_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='organization',
            field=models.CharField(blank=True, help_text="Organization label shown in this owner's contact list.", max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='location',
            field=models.CharField(blank=True, help_text='City/region set by the user; read-only for contacts.', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, help_text='User-defined nickname shown to their contacts.', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='organization',
            field=models.CharField(blank=True, help_text='Organization/company name shared with contacts.', max_length=255),
        ),
    ]
