# Generated by Django 5.2.4 on 2025-09-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_connection_organization_person_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='nickname',
        ),
        migrations.AddField(
            model_name='connection',
            name='nickname',
            field=models.CharField(blank=True, help_text='Personal nickname for this contact (owner-specific)', max_length=100),
        ),
    ]
