# Generated by Django 5.2.4 on 2025-10-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_event_options_alter_event_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('birthday', 'Birthday'), ('general', 'General'), ('work_meeting', 'Work Meeting'), ('deadline', 'Deadline'), ('party', 'Party'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('breakfast', 'Breakfast'), ('vacation', 'Vacation')], default='general', max_length=32),
        ),
    ]
