# Generated by Django 5.2.4 on 2025-10-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('birthday', 'Birthday'), ('general', 'General'), ('work_meeting', 'Work Meeting'), ('deadline', 'Deadline'), ('party', 'Party'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('breakfast', 'Breakfast'), ('vacation', 'Vacation'), ('other', 'Other')], default='general', max_length=32),
        ),
    ]
