# Generated by Django 5.2.4 on 2026-03-20 05:35

from django.db import migrations, models


def backfill_contact_email(apps, schema_editor):
    Person = apps.get_model("accounts", "Person")
    Person.objects.filter(contact_email__isnull=True).update(contact_email=models.F("email"))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_account_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='login_email_change_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='account',
            name='login_email_change_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='pending_login_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.RunPython(backfill_contact_email, noop_reverse),
    ]
